### ISSUE TITLE
add pre-commit hook?

### ISSUE THREAD

**Issue by ahgraber** [mistermicheels/markdown-notes-tree#7]
I think it would be very useful to use this as a [pre-commit hook](https://pre-commit.com/#pre-commit-configyaml---hooks).  I think all that is required is to add a `.pre-commit-hook.yaml` file to the repo

```yaml
-   id: markdown-notes-tree
    name: markdown-notes-tree
    description: '`markdown-notes-tree` will generate Markdown trees that act as a table of contents for the folder structure.'
    entry: markdown-notes-tree
    language: node
```
